# Generated by Django 5.2.16 on 2026-07-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_speechsession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sentence', models.TextField()),
                ('difficulty', models.CharField(default='easy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciation_score', models.FloatField()),
                ('accuracy_score', models.FloatField()),
                ('correct_words', models.IntegerField()),
                ('incorrect_words', models.IntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.exercise')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='speech.speechsession')),
            ],
        ),
    ]
